services:
  local-content-share-ttr:
    container_name: lcs-ttr
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5006:8080"
    volumes:
      - ./../data:/app/data
    restart: unless-stopped
