services:
  lcs-ttr:
    image: thetechrun/lcs-ttr:main
    pull_policy: always
    container_name: lcs-ttr
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - lcs-data:/app/data
    restart: unless-stopped
