services:
  local-content-share-ttr:
    container_name: lcs-ttr-dev
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5008:8080"
    volumes:
      - ../data:/app/data
    restart: unless-stopped